services:
  frontend:
    build:
      context: ./date_calculator
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - .env
    environment:
      PORT: "3000"
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./date_calculator:/app
      - /app/node_modules
    ports:
      - "3000:3000"
